#
# Makefile to build TeamSpeak 3 SDK Server FileTransfer Sample on FreeBSD 32-bit
#

CFLAGS = -Wall -g -O0

all: libs ts3_server_filetransfer_sample

libs: ../../bin/libts3server_freebsd_x86.so
	ln -sf ../../bin/libts3server_freebsd_x86.so .

ts3_server_filetransfer_sample: main.o
	gcc -o ts3_server_filetransfer_sample main.o -Wl,-rpath,"." -L../../bin -lts3server_freebsd_x86 -L/usr/local/lib -liconv -lpthread
	cp ts3_server_filetransfer_sample ../../bin

main.o: main.c
	gcc -c -I../../include main.c $(CFLAGS)

clean:
	rm -rf *.o ts3_server_filetransfer_sample
